### ISSUE TITLE
pom.xml compiler version 19 not 17?

### ISSUE THREAD

**Issue by adastomek** [drslock/JAVA2022#1]
Had an error when running `./mvnw clean compile` on `cw-shapes` template:
```shell
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] system modules path not set in conjunction with -source 17
[INFO] 1 warning
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] warnings found and -Werror specified
[INFO] 1 error
```
seems like [pom.xml](https://github.com/drslock/JAVA2022/blob/700e82d396ec0e22be93692ee62e222d659397fd/Weekly%20Workbooks/01%20Introduction%20to%20OOP/IntelliJ%20Template/cw-shapes/pom.xml) is specifies an older java 17 version:
```xml
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
```
Where we've been asked to use [version 19](https://github.com/drslock/JAVA2022/tree/main/Weekly%20Workbooks/01%20Introduction%20to%20OOP#task-3-intellij-idea)

Changing the version to 19 worked for me:
```xml
	<properties>
		<maven.compiler.source>19</maven.compiler.source>
		<maven.compiler.target>19</maven.compiler.target>
```
with the correct (i assume) `./mvnw exec:java` behaviour:

```shell
% ./mvnw exec:java    
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< comsm0086:cw-shapes >-------------------------
[INFO] Building cw-shapes 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ cw-shapes ---
Hello world!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.422 s
[INFO] Finished at: 2023-01-26T01:34:26Z
[INFO] ------------------------------------------------------------------------

```

**Comment by drslock** [comment]
The version of Java specified in the POM file should be the version of Java you have currently installed within your OS (rather than the version of Java you select when setting up the IntelliJ project). This is because you are running Maven on the command line (i.e. independently of IntelliJ). Typically people will have 17 installed, but might have a newer version - in which case you will need to update the POM file. The lab machines have 17 on them, so the POM file should work fine there. To find out which version of Java you have installed, run `java -version` on the command line. Anyone who is having trouble - talk to one of the HTPs in the lab.
